### ISSUE TITLE
what to do after tutorial 

### ISSUE THREAD

**Issue by PujanMotiwala** [evanphilipsmith/spreadsheet-finances#20]
I am still waiting for when I can add my bank creds to Plaid and then add the address to my google sheet where I can see specific data.

**Comment by PujanMotiwala** [comment]
./run_web_server.sh                                                                      ✔  took 4s  system  
Using Flask session manager
Traceback (most recent call last):
  File "/Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/site-packages/gsheets_plaid/__main__.py", line 5, in <module>
    from gsheets_plaid.web_server.main import run_web_server
  File "/Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/site-packages/gsheets_plaid/web_server/main.py", line 55, in <module>
    @app.before_first_request
AttributeError: 'Flask' object has no attribute 'before_first_request'. Did you mean: '_got_first_request'?

Also, 
install --upgrade flask                              ✔  system  

Requirement already satisfied: flask in /Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/site-packages (2.3.2)
Requirement already satisfied: Werkzeug>=2.3.3 in /Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/site-packages (from flask) (2.3.6)
Requirement already satisfied: Jinja2>=3.1.2 in /Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/site-packages (from flask) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in /Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/site-packages (from flask) (2.1.2)
Requirement already satisfied: click>=8.1.3 in /Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/site-packages (from flask) (8.1.6)
Requirement already satisfied: blinker>=1.6.2 in /Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/site-packages (from flask) (1.6.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/pujan/.pyenv/versions/3.10.4/lib/python3.10/site-packages (from Jinja2>=3.1.2->flask) (2.1.3)

**Comment by e13h** [comment]
Hi @PujanMotiwala, I did some digging and it looks like the `@app.before_first_request` decorator was recently removed from Flask 2.3. I'll have to update the code to work with the latest version of Flask.
